In [1]:
import nltk
import numpy as np
import bs4 as bs
import urllib.request
import re

In [2]:
raw_html=urllib.request.urlopen('https://en.wikipedia.org/wiki/Natural_language_processing')
raw_html

In [3]:
raw_html=raw_html.read()
print(raw_html)

b'<!DOCTYPE html>\n<html class="client-nojs" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8"/>\n<title>Natural language processing - Wikipedia</title>\n<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"cafabd64-2dda-4b73-9733-6ecee0ee4066","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Natural_language_processing","wgTitle":"Natural language processing","wgCurRevisionId":1014077025,"wgRevisionId":1014077025,"wgArticleId":21652,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 maint: location","Articles with short description","Short description matches Wikidata","Commons link from Wikidata"

In [4]:
atricle_html=bs.BeautifulSoup(raw_html,'lxml')
atricle_html

<!DOCTYPE html>
<html class="client-nojs" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Natural language processing - Wikipedia</title>
<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"cafabd64-2dda-4b73-9733-6ecee0ee4066","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Natural_language_processing","wgTitle":"Natural language processing","wgCurRevisionId":1014077025,"wgRevisionId":1014077025,"wgArticleId":21652,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 maint: location","Articles with short description","Short description matches Wikidata","Commons link from Wikidata","Wikip

In [5]:
article_paragraphs = atricle_html.find_all('p')#converting data to paragraphs
article_paragraphs 

[<p><b>Natural language processing</b> (<b>NLP</b>) is a subfield of <a href="/wiki/Linguistics" title="Linguistics">linguistics</a>, <a href="/wiki/Computer_science" title="Computer science">computer science</a>, and <a href="/wiki/Artificial_intelligence" title="Artificial intelligence">artificial intelligence</a> concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of <a href="/wiki/Natural_language" title="Natural language">natural language</a> data.  The result is a computer capable of "understanding" the contents of documents, including the contextual nuances of the language within them. The technology can then accurately extract information and insights contained in the documents as well as categorize and organize the documents themselves. 
 </p>,
 <p>Challenges in natural language processing frequently involve <a href="/wiki/Speech_recognition" title="Speech recognition">speech recognit

In [6]:
article_texts=''
for para in article_paragraphs:
    article_texts+=para.text
article_texts
#converting into single para

'Natural language processing (NLP) is a subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of natural language data.  The result is a computer capable of "understanding" the contents of documents, including the contextual nuances of the language within them. The technology can then accurately extract information and insights contained in the documents as well as categorize and organize the documents themselves. \nChallenges in natural language processing frequently involve speech recognition, natural language understanding, and natural-language generation.\nNatural language processing has its roots in the 1950s. Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence" which proposed what is now called the Turing test as a criterion of intelligence, a task that involves the automated i

In [7]:
w_token = nltk.word_tokenize(article_texts)
print(w_token)
len(w_token)

['Natural', 'language', 'processing', '(', 'NLP', ')', 'is', 'a', 'subfield', 'of', 'linguistics', ',', 'computer', 'science', ',', 'and', 'artificial', 'intelligence', 'concerned', 'with', 'the', 'interactions', 'between', 'computers', 'and', 'human', 'language', ',', 'in', 'particular', 'how', 'to', 'program', 'computers', 'to', 'process', 'and', 'analyze', 'large', 'amounts', 'of', 'natural', 'language', 'data', '.', 'The', 'result', 'is', 'a', 'computer', 'capable', 'of', '``', 'understanding', "''", 'the', 'contents', 'of', 'documents', ',', 'including', 'the', 'contextual', 'nuances', 'of', 'the', 'language', 'within', 'them', '.', 'The', 'technology', 'can', 'then', 'accurately', 'extract', 'information', 'and', 'insights', 'contained', 'in', 'the', 'documents', 'as', 'well', 'as', 'categorize', 'and', 'organize', 'the', 'documents', 'themselves', '.', 'Challenges', 'in', 'natural', 'language', 'processing', 'frequently', 'involve', 'speech', 'recognition', ',', 'natural', 'lang

1479

In [8]:
words_no_punc = []
for w in w_token:
    if w.isalpha():
        words_no_punc.append(w)
print(words_no_punc)
len(words_no_punc)

['Natural', 'language', 'processing', 'NLP', 'is', 'a', 'subfield', 'of', 'linguistics', 'computer', 'science', 'and', 'artificial', 'intelligence', 'concerned', 'with', 'the', 'interactions', 'between', 'computers', 'and', 'human', 'language', 'in', 'particular', 'how', 'to', 'program', 'computers', 'to', 'process', 'and', 'analyze', 'large', 'amounts', 'of', 'natural', 'language', 'data', 'The', 'result', 'is', 'a', 'computer', 'capable', 'of', 'understanding', 'the', 'contents', 'of', 'documents', 'including', 'the', 'contextual', 'nuances', 'of', 'the', 'language', 'within', 'them', 'The', 'technology', 'can', 'then', 'accurately', 'extract', 'information', 'and', 'insights', 'contained', 'in', 'the', 'documents', 'as', 'well', 'as', 'categorize', 'and', 'organize', 'the', 'documents', 'themselves', 'Challenges', 'in', 'natural', 'language', 'processing', 'frequently', 'involve', 'speech', 'recognition', 'natural', 'language', 'understanding', 'and', 'generation', 'Natural', 'langu

1178

In [9]:
from nltk.corpus import stopwords
stopwords = stopwords.words('english')
print(stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [10]:
clean_words=[]
for w in words_no_punc:
    if w not in stopwords:
        clean_words.append(w)
clean_words 

['Natural',
 'language',
 'processing',
 'NLP',
 'subfield',
 'linguistics',
 'computer',
 'science',
 'artificial',
 'intelligence',
 'concerned',
 'interactions',
 'computers',
 'human',
 'language',
 'particular',
 'program',
 'computers',
 'process',
 'analyze',
 'large',
 'amounts',
 'natural',
 'language',
 'data',
 'The',
 'result',
 'computer',
 'capable',
 'understanding',
 'contents',
 'documents',
 'including',
 'contextual',
 'nuances',
 'language',
 'within',
 'The',
 'technology',
 'accurately',
 'extract',
 'information',
 'insights',
 'contained',
 'documents',
 'well',
 'categorize',
 'organize',
 'documents',
 'Challenges',
 'natural',
 'language',
 'processing',
 'frequently',
 'involve',
 'speech',
 'recognition',
 'natural',
 'language',
 'understanding',
 'generation',
 'Natural',
 'language',
 'processing',
 'roots',
 'Already',
 'Alan',
 'Turing',
 'published',
 'article',
 'titled',
 'Computing',
 'Machinery',
 'Intelligence',
 'proposed',
 'called',
 'Turing',

In [14]:
wordfreq={}
for token in clean_words:
        if token not in wordfreq:
            wordfreq[token]=1
        else:
            wordfreq[token]+=1
print(wordfreq)
len(wordfreq)    

{'Natural': 3, 'language': 25, 'processing': 14, 'NLP': 16, 'subfield': 1, 'linguistics': 9, 'computer': 4, 'science': 3, 'artificial': 2, 'intelligence': 3, 'concerned': 1, 'interactions': 1, 'computers': 2, 'human': 2, 'particular': 1, 'program': 1, 'process': 2, 'analyze': 1, 'large': 3, 'amounts': 1, 'natural': 15, 'data': 5, 'The': 6, 'result': 1, 'capable': 1, 'understanding': 4, 'contents': 1, 'documents': 4, 'including': 1, 'contextual': 1, 'nuances': 1, 'within': 1, 'technology': 1, 'accurately': 1, 'extract': 1, 'information': 1, 'insights': 1, 'contained': 1, 'well': 1, 'categorize': 1, 'organize': 1, 'Challenges': 1, 'frequently': 2, 'involve': 2, 'speech': 2, 'recognition': 2, 'generation': 2, 'roots': 1, 'Already': 1, 'Alan': 1, 'Turing': 2, 'published': 1, 'article': 1, 'titled': 1, 'Computing': 1, 'Machinery': 1, 'Intelligence': 1, 'proposed': 1, 'called': 1, 'test': 1, 'criterion': 1, 'task': 3, 'involves': 1, 'automated': 1, 'interpretation': 1, 'time': 1, 'articulate

433

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=433)
B_O_W = cv.fit_transform(clean_words).toarray()

print(cv.get_feature_names())

['abandoned', 'accurately', 'achieve', 'acl', 'acquiring', 'action', 'addressed', 'advanced', 'advantage', 'advantages', 'age', 'ai', 'aid', 'alan', 'algorithms', 'alignment', 'along', 'already', 'although', 'among', 'amounts', 'analysis', 'analyze', 'annotations', 'answering', 'answers', 'apparent', 'applications', 'applied', 'applying', 'approach', 'approaches', 'area', 'areas', 'article', 'articulated', 'artificial', 'as', 'aspects', 'attaching', 'automated', 'automatically', 'based', 'became', 'behaviour', 'branch', 'broadly', 'build', 'cache', 'called', 'calls', 'capable', 'capture', 'categories', 'categorize', 'certainty', 'challenges', 'changes', 'chinese', 'chomskyan', 'classes', 'closely', 'coarse', 'cognition', 'cognitive', 'collection', 'combining', 'common', 'commonly', 'complex', 'component', 'comprehension', 'comprising', 'computational', 'computer', 'computers', 'computing', 'concerned', 'conferences', 'confronted', 'conll', 'construction', 'contained', 'contains', 'cont

In [16]:
print(cv.vocabulary_)

{'natural': 240, 'language': 198, 'processing': 279, 'nlp': 248, 'subfield': 355, 'linguistics': 211, 'computer': 74, 'science': 320, 'artificial': 36, 'intelligence': 183, 'concerned': 77, 'interactions': 185, 'computers': 75, 'human': 167, 'particular': 263, 'program': 283, 'process': 277, 'analyze': 22, 'large': 199, 'amounts': 20, 'data': 94, 'the': 373, 'result': 312, 'capable': 51, 'understanding': 400, 'contents': 84, 'documents': 114, 'including': 172, 'contextual': 87, 'nuances': 251, 'within': 414, 'technology': 369, 'accurately': 1, 'extract': 136, 'information': 176, 'insights': 179, 'contained': 82, 'well': 411, 'categorize': 54, 'organize': 258, 'challenges': 56, 'frequently': 149, 'involve': 193, 'speech': 343, 'recognition': 297, 'generation': 154, 'roots': 318, 'already': 17, 'alan': 13, 'turing': 394, 'published': 289, 'article': 34, 'titled': 384, 'computing': 76, 'machinery': 215, 'proposed': 286, 'called': 49, 'test': 372, 'criterion': 93, 'task': 364, 'involves': 

In [17]:
print(B_O_W)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=433)
X = vectorizer.fit_transform(clean_words).toarray()
print(vectorizer.vocabulary_)
print(vectorizer.get_feature_names())
print(X)

{'natural': 240, 'language': 198, 'processing': 279, 'nlp': 248, 'subfield': 355, 'linguistics': 211, 'computer': 74, 'science': 320, 'artificial': 36, 'intelligence': 183, 'concerned': 77, 'interactions': 185, 'computers': 75, 'human': 167, 'particular': 263, 'program': 283, 'process': 277, 'analyze': 22, 'large': 199, 'amounts': 20, 'data': 94, 'the': 373, 'result': 312, 'capable': 51, 'understanding': 400, 'contents': 84, 'documents': 114, 'including': 172, 'contextual': 87, 'nuances': 251, 'within': 414, 'technology': 369, 'accurately': 1, 'extract': 136, 'information': 176, 'insights': 179, 'contained': 82, 'well': 411, 'categorize': 54, 'organize': 258, 'challenges': 56, 'frequently': 149, 'involve': 193, 'speech': 343, 'recognition': 297, 'generation': 154, 'roots': 318, 'already': 17, 'alan': 13, 'turing': 394, 'published': 289, 'article': 34, 'titled': 384, 'computing': 76, 'machinery': 215, 'proposed': 286, 'called': 49, 'test': 372, 'criterion': 93, 'task': 364, 'involves': 